#!/usr/bin/env bash

API_URL="https://pokeapi.co/api/v2/pokemon"
POKEMAN=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")

mkdir -p pokemon_data

for p in "${POKEMAN[@]}"; do
    echo "Fetching data for $p..."
    curl -s "$API_URL/$p" -o "pokemon_data/$p.json"
    echo "Saved data to pokemon_data/$p.json"
    sleep 1
done
